server:
  port: ${PORT:9095}
logging:
  level:
    com.ss.challenge.votesessionmanagerapi: INFO
    org.springframework: INFO
    org.apache.kafka: INFO
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} app=${spring.application.name}
            %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint}
            %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} M=%M
            %m%n}'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  health:
    db:
      enabled: true
vote-session:
  api-cpf-generator:
    url: https://gerador.app/api
    token: Bearer BbjJ1DLBc9b6Qx8cmNggwKQCBlFQRVWO3q0HxFND
spring:
  application:
    name: vote-session-manager-api
  devtools:
    add-properties: false
    restart:
      log-condition-evaluation-delta:  false
  kafka:
    producer:
      acks: 1
      bootstrap-servers:
        - localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: mock://unused
    topics:
      result-vote-session: result-vote-session
    client-id: ${spring.application.name}
  datasource:
    url: jdbc:mysql://localhost:3306/testedb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: MySqlPass!
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: none
        default-schema: testedb
        dialect: org.hibernate.dialect.MySQLDialect
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
      generate-ddl: false
      show-sql: true
      platform: org.hibernate.dialect.MySQLDialect
      database: mysql

  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: true
    user: root
    password: MySqlPass!
    schemas: testedb
    url: jdbc:mysql://localhost:3306/testedb?allowPublicKeyRetrieval=true&useSSL=false


swagger:
  message:
    welcome: Vote Session Manager API
    description: 'API para gestão de sessões de votões'
    version: 1.0
    contact:
      name: Fernando meireles
      email: 'fernando.meireles.filho@gmail.com'


